### ISSUE TITLE
can't publish to yotube

### ISSUE THREAD

**Issue by JIEgOKOJI** [dustinblackman/streamroller#1]
Tried with OBS, youtube show that stream will start soon and nothing happens. Publish to other services works fine

**Comment by dustinblackman** [comment]
@JIEgOKOJI Need a bit more details. I've tested it just yesterday and Youtube was working. Could you paste me the RTMP url youtube gives you __without__ your stream key on the end please? Should look something like `rtmp://a.rtmp.youtube.com/live2/`

**Comment by JIEgOKOJI** [comment]
http://joxi.ru/YmEXDXhZnEvkr6.jpg  and this one http://joxi.ru/krDnDns01vwN2p.jpg

**Comment by JIEgOKOJI** [comment]
Tell me if i can provide more info. Also tested on CentOS7 with same result. Written my own application on GoLang using joy4 lib and it can't publish to youtube to. Tells that "remote server closed connection", also tested on my friend yotube account and same result

**Comment by dustinblackman** [comment]
@JIEgOKOJI Try adding the `--verbose` flag, it may help give some more insight. Also possibly try wrapping your live key in double quotes, though I'm not sure that'll help.

**Comment by JIEgOKOJI** [comment]
http://joxi.ru/8AngVgFqBlEyrO.jpg Here.

**Comment by dustinblackman** [comment]
I haven't been able to reproduce this issue. As we've both gone quiet I'll close it for now. Feel free to open a new issue if you're still having a problem.

**Comment by DRSchlaubi** [comment]
Got the same problem. streamroller says `2019-10-26T17:59:58.981+0200    INFO    services/youtube.go:55  Connecting to Youtube RTMP` but then it get's stuck there
